name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    # Additional steps to deploy your application can be added here
    - name: Deploy to Server
      run: |
        echo "Deploying to server..."
        # Your deployment script or commands go here
